#Gradle
org.gradle.jvmargs=-Xms12g -XX:+UseParallelGC -XX:MaxMetaspaceSize=5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon.idletimeout=120000

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true