import java.util.Properties

plugins {
    id("frnk.kmp.library.hosttest")
}

// The toolkit-wide PostHog project key is a build-time input, never a committed constant: every frnk
// app reports to the one project, so the key ships INSIDE the toolkit's binaries (Android AAR + the
// iOS klib every umbrella framework links), and no host supplies it — but this repo will be public,
// so the value lives in the gitignored `local.properties` of the frnk checkout (the submodule's, in
// a host), or in the `POSTHOG_API_KEY` env var / `-PPOSTHOG_API_KEY=` Gradle property for CI.
// `generateFrnkPostHogProject` writes it into `FrnkPostHogProject` under build/ and fails loudly when
// every source is blank. A `phc_…` project key is a public client key by design (it is embedded in
// every shipped binary and grants no read access) — the reason it can live in a binary at all.
val localProperties: Provider<Properties> =
    providers
        .fileContents(rootProject.layout.projectDirectory.file("local.properties"))
        .asText
        .map { text -> Properties().apply { load(text.reader()) } }
        .orElse(Properties())

fun buildInput(name: String): Provider<String> =
    providers
        .gradleProperty(name)
        .orElse(providers.environmentVariable(name))
        .orElse(localProperties.map { it.getProperty(name, "") })
        .map { it.trim() }

val generateFrnkPostHogProject by tasks.registering(GenerateFrnkPostHogProject::class) {
    apiKey.set(buildInput("POSTHOG_API_KEY"))
    host.set(buildInput("POSTHOG_HOST"))
    outputDir.set(layout.buildDirectory.dir("generated/frnkPostHog/commonMain/kotlin"))
}

kotlin {
    android {
        namespace = "${libs.versions.frnk.groupId.get()}.backend.posthog"
    }
    sourceSets {
        commonMain {
            kotlin.srcDir(generateFrnkPostHogProject)
            dependencies {
                api(projects.analyticsApi)
                implementation(libs.koin.core)
                implementation(libs.posthog.kmp)
            }
        }
        // PostHog's Android setup needs the Application; it comes from Koin's androidContext(),
        // which the Android initializeFrnk overload registers.
        androidMain.dependencies {
            implementation(libs.koin.android)
        }
    }
}

// posthog-ios is supplied by the consuming Xcode target (SPM product `PostHog`), so this module
// cannot link a standalone Kotlin/Native test executable. Its common tests still run via
// testAndroidHostTest; native linkage is verified by the demo Xcode integration build.
listOf("linkDebugTestIosSimulatorArm64", "iosSimulatorArm64Test").forEach { taskName ->
    tasks.named(taskName) {
        enabled = false
    }
}

@CacheableTask
abstract class GenerateFrnkPostHogProject : DefaultTask() {
    @get:Input
    abstract val apiKey: Property<String>

    @get:Input
    abstract val host: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val key = apiKey.get()
        check(key.isNotBlank()) {
            "POSTHOG_API_KEY is not set — frnk ships the toolkit-wide PostHog project key inside " +
                ":analytics-posthog, read at build time from the frnk checkout's local.properties " +
                "(gitignored; see local.properties.example), the POSTHOG_API_KEY environment variable, " +
                "or -PPOSTHOG_API_KEY=… . Hosts never pass it in code."
        }
        check(key.startsWith("phc_")) { "POSTHOG_API_KEY must be a PostHog project API key (phc_…), got '${key.take(4)}…'" }
        val hostExpr = host.get().ifBlank { "" }.let { if (it.isBlank()) "PostHogConfig.HOST_US" else "\"$it\"" }
        val file = outputDir.get().asFile.resolve("dev/jdgarita/frnk/backend/posthog/FrnkPostHogProject.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package dev.jdgarita.frnk.backend.posthog
            |
            |import com.posthog.kmp.PostHogConfig
            |
            |/**
            | * GENERATED by `:analytics-posthog`'s `generateFrnkPostHogProject` from `POSTHOG_API_KEY` /
            | * `POSTHOG_HOST` (frnk's gitignored `local.properties`, or the env var / `-P` property). Do not edit,
            | * do not commit a copy.
            | *
            | * The one PostHog project every frnk host reports to. Its API key is universal across the apps —
            | * it identifies the project, not an app — so it ships inside the toolkit's binaries and a host never
            | * supplies it: [PostHogAnalyticsConfig.apiKey] defaults to [API_KEY]. Apps are told apart inside
            | * PostHog by the SDK's `${'$'}app_namespace` / `${'$'}app_name` properties, debug vs release by the
            | * `environment` super property. A `phc_…` key is a public client key by design; the project's
            | * secret keys never enter the toolkit. Contrast Sentry: each app has its own project + DSN.
            | */
            |object FrnkPostHogProject {
            |    /** Project API key of the shared frnk PostHog project. */
            |    const val API_KEY: String = "$key"
            |
            |    /** Ingestion host of the project's region. */
            |    const val HOST: String = $hostExpr
            |}
            |
            """.trimMargin()
        )
    }
}