package dev.jdgarita.frnk.util.di

import org.koin.core.qualifier.StringQualifier

val httpClientKxsJsonQualifier = StringQualifier("httpClientKxsJson")

val viewModelDispatcherQualifier = StringQualifier("viewModelDispatcher")
val uiDispatcherQualifier = StringQualifier("uiDispatcher")
val backgroundDispatcherQualifier = StringQualifier("backgroundDispatcherQualifier")
val ioDispatcherQualifier = StringQualifier("ioDispatcherQualifier")
val analyticsDispatcherQualifier = StringQualifier("analyticsDispatcherQualifier")

val clearablesQualifier = StringQualifier("Clearables")

val authNavigationRouterQualifier = StringQualifier("AuthNavigationRouter")
val accountOnboardingNavigationRouterQualifier = StringQualifier("AccountOnboardingNavigationRouter")
val brandLandingPageNavigationRouterQualifier = StringQualifier("BrandLandingPageNavigationRouter")
val deleteAccountNavigationRouterQualifier = StringQualifier("DeleteAccountNavigationRouter")
val splashNavigationRouterQualifier = StringQualifier("SplashNavigationRouter")
val authorizedFlowStartEventQualifier = StringQualifier("AuthorizedFlowStartEvent")
val homeDealsNavigationRouterQualifier = StringQualifier("HomeDealsNavigationRouter")
val homeNavigationRouterQualifier = StringQualifier("HomeNavigationRouter")
val homeFullScreenNavigationRouterQualifier = StringQualifier("HomeFullScreenNavigationRouterQualifier")
val ageVerificationNavigationRouterQualifier = StringQualifier("AgeVerificationNavigationRouter")
val restrictedDealsNavigationRouterQualifier = StringQualifier("RestrictedDealsNavigationRouter")
val signUpNavigationRouterQualifier = StringQualifier("SignUpNavigationRouter")
val storeLocatorNavigationRouterQualifier = StringQualifier("StoreLocatorNavigationRouter")
val walletNavigationRouterQualifier = StringQualifier("WalletNavigationRouter")
val cashbackNavigationRouterQualifier = StringQualifier("CashbackNavigationRouter")
val componentLibNavigationRouterQualifier = StringQualifier("ComponentLibNavigationRouter")
val routingLinkToolNavigationRouterQualifier = StringQualifier("RoutingLinkToolNavigationRouter")
val productsNavigationRouterQualifier = StringQualifier("ProductsNavigationRouter")
val challengesNavigationRouterQualifier = StringQualifier("ChallengesNavigationRouter")
val navigationContextHandlersQualifier = StringQualifier("NavigationContextHandlers")
val routingLinkHandlersQualifier = StringQualifier("RoutingLinkHandler")
val scanNavigationRouterQualifier = StringQualifier("ScanNavigationRouter")
val cameraNavigationRouterQualifier = StringQualifier("CameraNavigationRouter")
val adsNavigationRouterQualifier = StringQualifier("AdsNavigationRouter")
val accountSettingsNavigationRouterQualifier = StringQualifier("AccountSettingsNavigationRouter")
val couponsNavigationRouterQualifier = StringQualifier("CouponsNavigationRouter")
val flyersNavigationRouterQualifier = StringQualifier("FlyersNavigationRouter")
val flyerFullscreenNavigationRouterQualifier = StringQualifier("FlyerFullscreenNavigationRouter")
val rewardsNavigationRouterQualifier = StringQualifier("RewardsNavigationRouter")
val updateShopperAccountNavigationRouterQualifier = StringQualifier("UpdateShopperAccountNavigationRouter")
val shoppingListNavigationRouterQualifier = StringQualifier("ShoppingListNavigationRouterQualifier")
val cartNavigationRouterQualifier = StringQualifier("CartNavigationRouterQualifier")
val cartFullScreenNavigationRouterQualifier = StringQualifier("CartFullScreenNavigationRouterQualifier")
val inboxNavigationRouterQualifier = StringQualifier("InboxNavigationRouter")
val tenantLoginNavigationRouterQualifier = StringQualifier("TenantLoginNavigationRouter")
val tenantLoginNavigationContextHandlerQualifier = StringQualifier("TenantLoginNavigationContextHandler")
val debugMenuNavigationRouterQualifier = StringQualifier("ConfigNavigationRouter")
val fulfillmentSelectorNavigationRouterQualifier = StringQualifier("fulfillmentSelectorNavigationRouterQualifier")

val authorizedRequesterQualifier = StringQualifier("ShopperAccountAuthorizedRequester")
val userContextRequesterQualifier = StringQualifier("UserContextRequester")

val cartCheckoutQualifier = StringQualifier("CartCheckoutQualifier")

val adsRemoteDataSource = StringQualifier("DefaultAdsRemoteDataSource")
val adsPlacementRemoteDataSource = StringQualifier("DefaultAdsPlacementRemoteDataSource")