@file:Suppress(
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:annotation"
)

package dev.jdgarita.frnk.presentation.resources.images

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
enum class SemanticImage {
    @ObjCName("addedNoRewards") AddedNoRewards,
    @ObjCName("brandLogoDark") BrandLogoDark,
    @ObjCName("brandLogoLight") BrandLogoLight,
    @ObjCName("browseNoRewards") BrowseNoRewards,
    @ObjCName("cardBannerOverThreshold") CardBannerOverThreshold,
    @ObjCName("cardBannerUpToThreshold") CardBannerUpToThreshold,
    @ObjCName("cashbackBalanceExplainer") CashbackBalanceExplainer,
    @ObjCName("clipNoCoupons") ClipNoCoupons,
    @ObjCName("fsaBadge") FSABadge,
    @ObjCName("hsaBadge") HSABadge,
    @ObjCName("imageZoom") ImageZoom,
    @ObjCName("loyaltyCardBannerLeading") LoyaltyCardBannerLeading,
    @ObjCName("loyaltyCardBannerTrailing") LoyaltyCardBannerTrailing,
    @ObjCName("loyaltyCardConnect") LoyaltyCardConnect,
    @ObjCName("orderDeliveryBakeryDessertsBanner") OrderDeliveryBakeryDessertsBanner,
    @ObjCName("orderDeliveryBanner") OrderDeliveryBanner,
    @ObjCName("orderDeliveryCateringBanner") OrderDeliveryCateringBanner,
    @ObjCName("orderDeliveryFlowersGiftsBanner") OrderDeliveryFlowersGiftsBanner,
    @ObjCName("orderGroceryDeliveryBanner") OrderGroceryDeliveryBanner,
    @ObjCName("orderGroceryDeliveryDoorDashBanner") OrderGroceryDeliveryDoorDashBanner,
    @ObjCName("orderGroceryDeliveryShiptBanner") OrderGroceryDeliveryShiptBanner,
    @ObjCName("orderPickupBakeryDessertsBanner") OrderPickupBakeryDessertsBanner,
    @ObjCName("orderPickupBanner") OrderPickupBanner,
    @ObjCName("orderPickupCateringBanner") OrderPickupCateringBanner,
    @ObjCName("orderPickupFlowersGiftsBanner") OrderPickupFlowersGiftsBanner,
    @ObjCName("paypal") Paypal,
    @ObjCName("pinMyStore") PinMyStore,
    @ObjCName("pinMyStoreFocused") PinMyStoreFocused,
    @ObjCName("pinStandard") PinStandard,
    @ObjCName("pinStandardFocused") PinStandardFocused,
    @ObjCName("plasticSurface") PlasticSurface,
    @ObjCName("plasticSurfaceLeft") PlasticSurfaceLeft,
    @ObjCName("plasticSurfaceRight") PlasticSurfaceRight,
    @ObjCName("redeemedNoCoupons") RedeemedNoCoupons,
    @ObjCName("redeemedNoRewards") RedeemedNoRewards,
    @ObjCName("setYourStore") SetYourStore,
    @ObjCName("shareYourLocation") ShareYourLocation,
    @ObjCName("shoppingListOnboardingNarrative1") ShoppingListOnboardingNarrative1,
    @ObjCName("shoppingListOnboardingNarrative2") ShoppingListOnboardingNarrative2,
    @ObjCName("shoppingListOnboardingNarrative3") ShoppingListOnboardingNarrative3,
    @ObjCName("snapBadge") SnapBadge,
    @ObjCName("swiftlyCouponImage") SwiftlyCouponImage,
    @ObjCName("swiftlyProductImage") SwiftlyProductImage,
    @ObjCName("swiftlyRewardImage") SwiftlyRewardImage,
    @ObjCName("venmo") Venmo,
    @ObjCName("walletAnonymousBanner") WalletAnonymousBanner,
    @ObjCName("walletAnonymousNarrative1") WalletAnonymousNarrative1,
    @ObjCName("walletAnonymousNarrative2") WalletAnonymousNarrative2,
    @ObjCName("walletAnonymousNarrative3") WalletAnonymousNarrative3,
    @ObjCName("walletAnonymousNarrative4") WalletAnonymousNarrative4,
    @ObjCName("walletAnonymousNarrative5") WalletAnonymousNarrative5,
    @ObjCName("walletAnonymousNarrative6") WalletAnonymousNarrative6,
    @ObjCName("walletAnonymousNarrative7") WalletAnonymousNarrative7,
    @ObjCName("walletAnonymousNarrative8") WalletAnonymousNarrative8,
    @ObjCName("walletAnonymousNarrative9") WalletAnonymousNarrative9,
    @ObjCName("walletAnonymousNarrative10") WalletAnonymousNarrative10,
    @ObjCName("walletAnonymousNarrative11") WalletAnonymousNarrative11,
    @ObjCName("walletAnonymousNarrative12") WalletAnonymousNarrative12,
    @ObjCName("walletAnonymousNarrative13") WalletAnonymousNarrative13,
    @ObjCName("walletAnonymousNarrative14") WalletAnonymousNarrative14,
    @ObjCName("walletAnonymousNarrative15") WalletAnonymousNarrative15,
    @ObjCName("walletExplainerBanner") WalletExplainerBanner,
    @ObjCName("walletExplainerNarrative1") WalletExplainerNarrative1,
    @ObjCName("walletExplainerNarrative2") WalletExplainerNarrative2,
    @ObjCName("walletExplainerNarrative3") WalletExplainerNarrative3,
    @ObjCName("walletExplainerNarrative4") WalletExplainerNarrative4,
    @ObjCName("walletExplainerNarrative5") WalletExplainerNarrative5,
    @ObjCName("walletExplainerNarrative6") WalletExplainerNarrative6,
    @ObjCName("walletExplainerNarrative7") WalletExplainerNarrative7,
    @ObjCName("walletExplainerNarrative8") WalletExplainerNarrative8,
    @ObjCName("walletExplainerNarrative9") WalletExplainerNarrative9,
    @ObjCName("walletExplainerNarrative10") WalletExplainerNarrative10,
    @ObjCName("walletExplainerNarrative11") WalletExplainerNarrative11,
    @ObjCName("walletExplainerNarrative12") WalletExplainerNarrative12,
    @ObjCName("walletExplainerNarrative13") WalletExplainerNarrative13,
    @ObjCName("walletExplainerNarrative14") WalletExplainerNarrative14,
    @ObjCName("walletExplainerNarrative15") WalletExplainerNarrative15,
    @ObjCName("warning65") Warning65,
    @ObjCName("welcomePage1") WelcomePage1,
    @ObjCName("welcomePage2") WelcomePage2,
    @ObjCName("welcomePage3") WelcomePage3,
    @ObjCName("welcomePage4") WelcomePage4,
    @ObjCName("welcomePage5") WelcomePage5,
    @ObjCName("welcomePage6") WelcomePage6,
    @ObjCName("welcomePage7") WelcomePage7,
    @ObjCName("welcomePage8") WelcomePage8,
    @ObjCName("welcomePage9") WelcomePage9,
    @ObjCName("welcomePage10") WelcomePage10
}