@file:Suppress(
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:annotation"
)

package dev.jdgarita.frnk.presentation.resources.images

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import kotlinx.serialization.Serializable

@OptIn(ExperimentalObjCName::class)
@Serializable
enum class SemanticIcon {
    // Aligned with Figma - pending comments
    // >>> Please keep in alphabetical order <<<
    @ObjCName("account") Account,
    @ObjCName("add") Add,
    @ObjCName("added") Added,
    @ObjCName("aisle") Aisle,
    @ObjCName("arrowBack") ArrowBack,
    @ObjCName("arrowDropDown") ArrowDropDown,
    @ObjCName("arrowDropUp") ArrowDropUp,
    @ObjCName("arrowLeft") ArrowLeft,
    @ObjCName("arrowNext") ArrowNext,
    @ObjCName("arrowOut") ArrowOut,
    @ObjCName("arrowPrevious") ArrowPrevious,
    @ObjCName("arrowRight") ArrowRight,
    @ObjCName("camera") Camera,
    @ObjCName("cancel") Cancel,
    @ObjCName("check") Check,
    @ObjCName("checkBoxFilled") CheckBoxFilled,
    @ObjCName("checkBoxOutline") CheckBoxOutline,
    @ObjCName("clip") Clip,
    @ObjCName("close") Close,
    @ObjCName("copy") Copy,
    @ObjCName("delete") Delete,
    @ObjCName("directions") Directions,
    @ObjCName("error") Error,
    @ObjCName("filter") Filter,
    @ObjCName("flashOff") FlashOff,
    @ObjCName("flashOn") FlashOn,
    @ObjCName("help") Help,
    @ObjCName("history") History,
    @ObjCName("inbox") Inbox,
    @ObjCName("inboxNotification") InboxNotification,
    @ObjCName("info") Info,
    @ObjCName("inStore") InStore,
    @ObjCName("keyList") KeyList,
    @ObjCName("keyProducts") KeyProducts,
    @ObjCName("keyShop") KeyShop,
    @ObjCName("location") Location,
    @ObjCName("lock") Lock,
    @ObjCName("mapStore") MapStore,
    @ObjCName("minus") Minus,
    @ObjCName("more") More,
    @ObjCName("myLocation") MyLocation,
    @ObjCName("myStore") MyStore,
    @ObjCName("noResults") NoResults,
    @ObjCName("noWifi") NoWifi,
    @ObjCName("paymentMethods") PaymentMethods,
    @ObjCName("pencil") Pencil,
    @ObjCName("pending") Pending,
    @ObjCName("phone") Phone,
    @ObjCName("pickup") Pickup,
    @ObjCName("plus") Plus,
    @ObjCName("pointHistBalance") PointHistBalance,
    @ObjCName("pointHistCashed") PointHistCashed,
    @ObjCName("pointHistChallenge") PointHistChallenge,
    @ObjCName("pointHistExpired") PointHistExpired,
    @ObjCName("pointHistGeneric") PointHistGeneric,
    @ObjCName("pointHistPurchase") PointHistPurchase,
    @ObjCName("pointHistReward") PointHistReward,
    @ObjCName("productAttribute") ProductAttribute,
    @ObjCName("productCurrency") ProductCurrency,
    @ObjCName("productLoyalty") ProductLoyalty,
    @ObjCName("productSale") ProductSale,
    @ObjCName("radioChecked") RadioChecked,
    @ObjCName("radioUnchecked") RadioUnchecked,
    @ObjCName("receipt") Receipt,
    @ObjCName("redeemedCoupons") RedeemedCoupons,
    @ObjCName("redeemedRewards") RedeemedRewards,
    @ObjCName("refine") Refine,
    @ObjCName("refresh") Refresh,
    @ObjCName("rewards") Rewards,
    @ObjCName("scan") Scan,
    @ObjCName("search") Search,
    @ObjCName("share") Share,
    @ObjCName("shop") Shop,
    @ObjCName("shoppingBag") ShoppingBag,
    @ObjCName("sun") Sun,
    @ObjCName("tabAccount") TabAccount,
    @ObjCName("tabCircular") TabCircular,
    @ObjCName("tabHome") TabHome,
    @ObjCName("tabList") TabList,
    @ObjCName("tabPharmacy") TabPharmacy,
    @ObjCName("tabRewards") TabRewards,
    @ObjCName("tabScan") TabScan,
    @ObjCName("tabShop") TabShop,
    @ObjCName("trophy") Trophy,
    @ObjCName("trophyFilled") TrophyFilled,
    @ObjCName("viewFinder") ViewFinder,
    @ObjCName("visibility") Visibility,
    @ObjCName("visibilityOff") VisibilityOff,
    @ObjCName("warning") Warning,
    @ObjCName("wrongDate") WrongDate,
    @ObjCName("wrongLocation") WrongLocation,
    @ObjCName("xmark") Xmark,
    @ObjCName("zoomOut") ZoomOut
}