package dev.jdgarita.frnk.presentation.mvi

import kotlinx.coroutines.flow.Flow

/**
 * This is the representation of a View Model with MVI.
 */
interface MviViewModel<TArgs : Arguments, TIntent : Intent, TViewState : ViewState, TExternalEvent : ExternalEvent> :
    LifecycleAware<TArgs> {
    val viewState: TViewState

    val viewStateFlow: Flow<TViewState>

    val externalEventFlow: Flow<ExternalEvent>

    fun onIntent(intent: TIntent)

    fun onIntent(intent: CommonIntent)

    // Support for platforms w/o Flow support (e.g. JS)
    /**
     * Subscribes to the view state flow and receives update via callback.
     *
     * NOTE: The lifecycle of this subscription is tied to the view being
     * *active*.  When the view becomes detached, the subscription will end.
     */
    fun subscribeViewState(onUpdate: (TViewState) -> Unit)

    /**
     * Subscribes to the external event flow and receives update via callback.
     *
     * NOTE: The lifecycle of this subscription is tied to the current view being
     * *attached*.  When the view becomes detached, the subscription will end.
     */
    fun subscribeExternalEvents(onEvent: (ExternalEvent) -> Unit)

    /**
     * Explicitly cancel any callback subscriptions
     */
    fun cancelCallbackSubscriptions()
}

interface LifecycleAware<TArgs : Arguments> {
    /**
     * The current lifecycle state of the View Model
     */
    val lifecycleState: LifecyleState

    /**
     * Call to bind a view to this ViewModel.
     *
     * This must be called before any other lifecycle states.  Once called, the lifecycle state
     * will transition from [LifecyleState.UNATTACHED] to [LifecyleState.ATTACHED]
     *
     * @param args The parameters needed to initialize the ViewModel with the context
     */
    fun attachView(args: TArgs)

    /**
     * Activate the ViewModel.  Call this when the bound view becomes visible or needs to be
     * re-activated after previously being deactivated.
     *
     * This will throw an IllegalStateException if the view does not have a view bound
     * (e.g. still in [LifecyleState.UNATTACHED]).
     *
     * This will be ignored if already active.
     */
    fun activate()

    /**
     * Deactivate the ViewModel.  Call this when the bound view becomes hidden or needs to be paused
     * for any other reason.
     *
     * This will be ignored if not in the [LifecyleState.ACTIVE] state.
     */
    fun deactivate()

    /**
     * The view has been detached.
     *
     * This will return the state to [LifecyleState.UNATTACHED]
     */
    fun detachView()

    /**
     * Check if the ViewModel has been activated
     */
    val active: Boolean
}

/**
 * The state that a view should render
 */
interface ViewState

/**
 * The representation of an action to feed to a View Model
 */
interface Intent

/**
 * An event that can be generated by a ViewModel.
 */
interface ExternalEvent : Arguments

/**
 * The Arguments that are used to initialize a View Model in the context of a View
 */
interface Arguments

enum class LifecyleState {
    UNATTACHED, // Unattached
    ATTACHED, // Attached, inactive
    ACTIVE // Attached, active
}